"""add created_at to jobs

Revision ID: 3f94383d01d2
Revises: f4fbc0e9bef8
Create Date: 2026-09-28 00:24:57.431324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f94383d01d2'
down_revision: Union[str, Sequence[str], None] = 'f4fbc0e9bef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # add the column empty first - adding it with the now() default would stamp
    # every existing job with the migration time and skew "jobs added per week"
    op.add_column('jobs', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))

    # best available guess for existing jobs; ones without a date applied stay NULL
    # noon UTC so the calendar date stays the same when shown in any US/EU/Asia timezone
    op.execute("UPDATE jobs SET created_at = date_applied + interval '12 hours' WHERE date_applied IS NOT NULL")

    # new jobs get the insert time from here on
    op.alter_column('jobs', 'created_at', server_default=sa.text('now()'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'created_at')
    # ### end Alembic commands ###
